//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newSite11_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public Keyword()
        {
            this.PhotoKeywords = new HashSet<PhotoKeyword>();
        }
    
        public int Id { get; set; }
        public string keywordText { get; set; }
    
        public virtual ICollection<PhotoKeyword> PhotoKeywords { get; set; }
    }
}
