//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newSite11_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public Photo()
        {
            this.PhotoKeywords = new HashSet<PhotoKeyword>();
            this.UserPhotos = new HashSet<UserPhoto>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public int likesNO { get; set; }
        public int commentsNO { get; set; }
        public Nullable<int> sharesNO { get; set; }
        public int albumID { get; set; }
        public string FBID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual ICollection<PhotoKeyword> PhotoKeywords { get; set; }
        public virtual ICollection<UserPhoto> UserPhotos { get; set; }
    }
}
