//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newSite11_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoKeyword
    {
        public int Id { get; set; }
        public int photo_photoID { get; set; }
        public int keyword_keywordID { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
